# 概要
本NoteBookは、[im2col徹底理解](https://qiita.com/kuroitu/items/35d7b5a4bde470f69570)を理解するために書いたコード集である。

In [2]:
import numpy as np

In [5]:
image = np.array(
    [[1,  2,  3,  4,],
     [5,  6,  7,  8,],
     [9,  10, 11, 12,],
     [13, 14, 15, 16,],]
)

print(image)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [6]:
F_h, F_w, O_h, O_w = 2, 2, 3, 3

In [17]:
col = np.empty((F_h, F_w, O_h, O_w))

for h in range(F_h):
    for w in range(F_w):
        col[h, w, :, :] = image[h : h+O_h, w : w+O_w]

print(col)

col = col.reshape(F_h*F_w, O_h*O_w)
print(col)



[[[[ 1.  2.  3.]
   [ 5.  6.  7.]
   [ 9. 10. 11.]]

  [[ 2.  3.  4.]
   [ 6.  7.  8.]
   [10. 11. 12.]]]


 [[[ 5.  6.  7.]
   [ 9. 10. 11.]
   [13. 14. 15.]]

  [[ 6.  7.  8.]
   [10. 11. 12.]
   [14. 15. 16.]]]]
[[ 1.  2.  3.  5.  6.  7.  9. 10. 11.]
 [ 2.  3.  4.  6.  7.  8. 10. 11. 12.]
 [ 5.  6.  7.  9. 10. 11. 13. 14. 15.]
 [ 6.  7.  8. 10. 11. 12. 14. 15. 16.]]


[[[[ 1.  2.  3.]
   [ 5.  6.  7.]
   [ 9. 10. 11.]]

  [[ 2.  3.  4.]
   [ 6.  7.  8.]
   [10. 11. 12.]]]


 [[[ 5.  6.  7.]
   [ 9. 10. 11.]
   [13. 14. 15.]]

  [[ 6.  7.  8.]
   [10. 11. 12.]
   [14. 15. 16.]]]]
